### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by terrorcide** [fabiensanglard/chocolate_duke3D#49]
Hi

I have just tried to build Chocolate Duke 3D on Xubuntu - and I receive a number of errors.

It appears that a number of these are due to certain files, including enet.h expecting other header files to be in a enet directory, however they are actually located in enet/include

e.g.

```
In file included from mmulti.c:21:0:
**enet/include/enet.h:18:23: fatal error: enet/unix.h: No such file or directory**
compilation terminated.
Makefile:448: recipe for target 'libEngine_a-mmulti.o' failed
```
I can manually change these files so they refer to the correct relative path.

Am I doing something wrong?

**Comment by FenzaFenz** [comment]
Same problem.

**Comment by darealshinji** [comment]
This is a bug in the source. There are two open pull requests that would fix this.

**Comment by rstevenson1976** [comment]
I'm having the same issue nearly 2 years later, still no fix?

**Comment by fabiensanglard** [comment]
Try to pull and build again.
